# Generated by Django 3.1.3 on 2020-12-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='maessage',
            new_name='message',
        ),
    ]
